# .github/workflows/deploy-production.yml

name: Deploy to Production

on:
  workflow_dispatch:  # 手動でのトリガー

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. SSH接続のセットアップ（秘密鍵を使用）
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # 3. DockerとDocker Composeのインストール
    - name: Set up Docker and Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # 4. EC2にデプロイ
    - name: Deploy to EC2 Production Server
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.PRODUCTION_EC2_IP }} << EOF
          # EC2サーバー内で実行するコマンド
          cd /var/www/html  # プロジェクトのディレクトリに移動
          git pull origin staging  # stagingブランチをプル
          docker-compose -f docker-compose.yml up -d --build  # Dockerコンテナを再ビルドして起動
        EOF

